//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProyecto.RefUsuarios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RefUsuarios.IServUsuario")]
    public interface IServUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServUsuario/validaLogin", ReplyAction="http://tempuri.org/IServUsuario/validaLoginResponse")]
        string validaLogin(string usua, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServUsuario/validaLogin", ReplyAction="http://tempuri.org/IServUsuario/validaLoginResponse")]
        System.Threading.Tasks.Task<string> validaLoginAsync(string usua, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServUsuario/RegistrarUsuario", ReplyAction="http://tempuri.org/IServUsuario/RegistrarUsuarioResponse")]
        string RegistrarUsuario(string nombre, string contra, string celular, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServUsuario/RegistrarUsuario", ReplyAction="http://tempuri.org/IServUsuario/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<string> RegistrarUsuarioAsync(string nombre, string contra, string celular, string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServUsuarioChannel : WebProyecto.RefUsuarios.IServUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServUsuarioClient : System.ServiceModel.ClientBase<WebProyecto.RefUsuarios.IServUsuario>, WebProyecto.RefUsuarios.IServUsuario {
        
        public ServUsuarioClient() {
        }
        
        public ServUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string validaLogin(string usua, string pass) {
            return base.Channel.validaLogin(usua, pass);
        }
        
        public System.Threading.Tasks.Task<string> validaLoginAsync(string usua, string pass) {
            return base.Channel.validaLoginAsync(usua, pass);
        }
        
        public string RegistrarUsuario(string nombre, string contra, string celular, string correo) {
            return base.Channel.RegistrarUsuario(nombre, contra, celular, correo);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarUsuarioAsync(string nombre, string contra, string celular, string correo) {
            return base.Channel.RegistrarUsuarioAsync(nombre, contra, celular, correo);
        }
    }
}
